import { Project } from './types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'PRJ-201',
    name: 'NH-24 Expansion (Block C)',
    category: 'Roads',
    status: 'Ongoing',
    progress: 65,
    budget: 45000000,
    zilla: 'Mysuru',
    taluk: 'Hunsur',
    gp: 'Rampur',
    village: 'Seelampur',
    address: 'Main Highway Road, near Seelampur junction',
    sanctionOrderNo: 'SO-101/2024',
    startDate: '2024-01-15',
    completionDate: '2024-12-30',
    description: 'Expansion of the existing two-lane highway to a four-lane divided carriageway to improve connectivity and reduce travel time.',
    history: 'The NH-24 stretch has seen a 40% increase in traffic over the last 5 years, leading to frequent bottlenecks and accidents.',
    workDone: 'Earthwork completed, 60% of the sub-base laid, and drainage construction is in progress.',
    beneficiaries: 50000,
    fundingSource: 'Central Government',
    coordinates: { lat: 12.3085, lng: 76.6447 },
    isPublic: true,
    isFeatured: true,
    photos: [
      { url: 'https://picsum.photos/seed/road1/800/600', caption: 'Initial site clearing', date: '2024-01-20' },
      { url: 'https://picsum.photos/seed/road2/800/600', caption: 'Sub-base preparation', date: '2024-03-15' },
      { url: 'https://picsum.photos/seed/road3/800/600', caption: 'Drainage work', date: '2024-05-10' },
    ],
    videos: [
      { url: 'https://www.w3schools.com/html/mov_bbb.mp4', caption: 'Progress update May 2024', thumbnail: 'https://picsum.photos/seed/vid1/400/225' }
    ]
  },
  {
    id: 'PRJ-202',
    name: 'Primary School Solar Grid',
    category: 'Education',
    status: 'Planned',
    progress: 0,
    budget: 1200000,
    zilla: 'Mysuru',
    taluk: 'Mysuru',
    gp: 'City',
    village: 'Rampur',
    sanctionOrderNo: 'SO-105/2024',
    startDate: '2024-06-01',
    description: 'Installation of a 10kW solar power grid to provide uninterrupted electricity to the primary school.',
    beneficiaries: 250,
    fundingSource: 'MPLADS',
    isPublic: true,
    photos: [{ url: 'https://picsum.photos/seed/solar/800/600', caption: 'Proposed site' }]
  },
  {
    id: 'PRJ-203',
    name: 'Community Health Center Renovation',
    category: 'Healthcare',
    status: 'Completed',
    progress: 100,
    budget: 8500000,
    zilla: 'Mysuru',
    taluk: 'Hunsur',
    gp: 'Rampur',
    village: 'Rampur',
    sanctionOrderNo: 'SO-110/2023',
    startDate: '2023-08-10',
    completionDate: '2024-02-15',
    description: 'Complete renovation of the existing health center including new maternity ward and laboratory equipment.',
    beneficiaries: 12000,
    fundingSource: 'State Government',
    isPublic: true,
    photos: [
      { url: 'https://picsum.photos/seed/health1/800/600', caption: 'Renovated exterior' },
      { url: 'https://picsum.photos/seed/health2/800/600', caption: 'New maternity ward' }
    ]
  },
  {
    id: 'PRJ-204',
    name: 'Drinking Water Pipeline - Phase 1',
    category: 'Water',
    status: 'Ongoing',
    progress: 40,
    budget: 25000000,
    zilla: 'Mysuru',
    taluk: 'Hunsur',
    gp: 'Rampur',
    village: 'Seelampur',
    sanctionOrderNo: 'SO-115/2024',
    startDate: '2024-02-01',
    description: 'Laying of 15km pipeline to provide clean drinking water to 5 villages.',
    beneficiaries: 8000,
    fundingSource: 'Central Government',
    isPublic: true,
    photos: [{ url: 'https://picsum.photos/seed/water/800/600', caption: 'Pipeline laying' }]
  },
  {
    id: 'PRJ-205',
    name: 'Smart Classroom Initiative',
    category: 'Education',
    status: 'Completed',
    progress: 100,
    budget: 500000,
    zilla: 'Mysuru',
    taluk: 'Mysuru',
    gp: 'City',
    village: 'Mysuru',
    sanctionOrderNo: 'SO-120/2023',
    startDate: '2023-11-01',
    completionDate: '2024-01-20',
    description: 'Equipping 10 government schools with interactive smart boards and digital content.',
    beneficiaries: 3000,
    fundingSource: 'MPLADS',
    isPublic: true,
    photos: [{ url: 'https://picsum.photos/seed/smart/800/600', caption: 'Smart board installation' }]
  },
  {
    id: 'PRJ-206',
    name: 'Veterinary Clinic Construction',
    category: 'Agriculture',
    status: 'Planned',
    progress: 0,
    budget: 4500000,
    zilla: 'Mysuru',
    taluk: 'Hunsur',
    gp: 'Rampur',
    village: 'Rampur',
    sanctionOrderNo: 'SO-125/2024',
    startDate: '2024-08-15',
    description: 'New veterinary clinic to serve the local farming community and livestock.',
    beneficiaries: 1500,
    fundingSource: 'State Government',
    isPublic: true
  }
];
