
import { Contact } from './types';

export const MOCK_CONTACTS: Contact[] = [
  {
    id: '1',
    name: 'Dr. Rajesh Kumar',
    designation: 'District Magistrate',
    organization: 'District Administration',
    category: 'Government Official',
    state: 'Karnataka',
    zilla: 'Mysuru',
    taluk: 'Mysuru',
    gp: 'City',
    village: 'Mysuru',
    mobile: '9876543210',
    email: 'dm.mysuru@gov.in',
    isVip: true,
    photoUrl: 'https://picsum.photos/seed/rajesh/200/200',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Smt. Lakshmi Devi',
    designation: 'GP President',
    organization: 'Rampur Gram Panchayat',
    category: 'Political Leader',
    state: 'Karnataka',
    zilla: 'Mysuru',
    taluk: 'Hunsur',
    gp: 'Rampur',
    village: 'Rampur',
    mobile: '9876543211',
    email: 'lakshmi.gp@gmail.com',
    isVip: false,
    createdAt: '2024-02-10',
  },
  {
    id: '3',
    name: 'Sri. Mohan Das',
    designation: 'Social Worker',
    organization: 'Seva Trust',
    category: 'Community Head',
    state: 'Karnataka',
    zilla: 'Mysuru',
    taluk: 'Mysuru',
    gp: 'City',
    village: 'Mysuru',
    mobile: '9876543212',
    email: 'mohan.das@trust.org',
    isVip: true,
    createdAt: '2024-03-01',
  },
  {
    id: '4',
    name: 'Anjali Sharma',
    designation: 'Reporter',
    organization: 'News 24',
    category: 'Media',
    state: 'Karnataka',
    zilla: 'Mysuru',
    taluk: 'Mysuru',
    gp: 'City',
    village: 'Mysuru',
    mobile: '9876543213',
    email: 'anjali.s@news24.com',
    isVip: false,
    photoUrl: 'https://picsum.photos/seed/anjali/200/200',
    createdAt: '2024-03-05',
  },
];
